apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  content: |
    statusStyle: dot
    cardBlur: xl
    theme: dark
    background:
      image: https://images.unsplash.com/photo-1485470733090-0aae1788d5af?q=80&w=3634&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
    layout:
      Infrastructure:
        style: row
        columns: 4
      Services:
        style: row
        columns: 4
      Media:
        style: row
        columns: 4
      System Info:
        style: row
        columns: 2
        pve-1:
          style: row
          columns: 2
        pve-2:
          style: row
          columns: 2
      Bookmarks:
        style: row
        columns: 3
